### ISSUE TITLE
Hardware Wallet: Trezor Support

### ISSUE THREAD

**Issue by prusnak** [zkSNACKs/Meta#30]
Wasabi wallet is a very good step towards Bitcoin fungibility/privacy. However, without hardware wallets support this makes people again vulnerable against coin-stealing malware. Let's add Trezor support to Wasabi!

There is already a library for interacting with Trezor:
* https://www.nuget.org/packages/Trezor.Net/
* https://github.com/MelbourneDeveloper/Trezor.Net

Reach me via email (stick@satoshilabs.com - put your postal address + phone number there) if you are a Wasabi developer and you want Trezor devices for testing.

**Comment by dpc** [comment]
@prusnak I think this requirement is going to happen more and more often - people will want hardware wallets to sign stuff automatically, just like @nopara73 mentioned

How about Trezor added a functionality, that one would be able to "trust" a `xpub`, and sign some form of a document that would make Trezor auto-sign transactions when the transactions submitted for signing comes with a proof that was signed this way.

Ideally, some form of a predicate-based language would be accepted to allow user to specify arbitrary rules, but that's complicated and huge surface for bugs, so right now Trezor could start with something of a form:

from_account: HD Path
to_account: HD Path
max_total_fee: Number
max_fee_per_sat: Number
min_ratio: 0-100%
min_locktime: Height
max_locktime: Height

after user confirms and signs a document like that with the Trezor, Wallets like Wasabi could be left ON with Trezor attached, and coinjoin coins from `from_account` to `to_account`, and Trezor would auto-sign all txes that have a ratio of funds from `from_account` to `to_account` at least that many percent, and fees not higher than specified. `locktime` would be more of a help for the user  to limit the duration of a trust, as I don't believe it can be fully enforced.

I am not sure if all of this is enough to be compat with the way wallets like Wasabi do CoinJoin, but I just wanted to point to the general idea: sign something with Trezor beforehand, that allows Wasabi to coinjoin when the users is AFK, as long as the Trezor is still present. Maybe not a perfect, but good-enough for many people, I believe.

**Comment by prusnak** [comment]
@dpc what is the point of Coinjoin if you can derive recipients via a simple XPUB?

**Comment by dpc** [comment]
@prusnak I might be wrong about something here, but I though coinjoin builds a n-inputs m-outputs tx where one of inputs is mine from my from_account and one output is mine to my to-account. Something that Trezor could check against a signed document. If multiple txs are involved or is something else entirely than tough luck.

**Comment by prusnak** [comment]
@dpc I understand what you meant now, the xpub part confused me.

@nopara73 You mentioned "rate limit to 5 times a day" - is this hardcoded in CJ protocol? Or this is just an arbitrary setting mentioned as an example?

**Comment by dpc** [comment]
@nopara73 rate limiting would require Trezor remember stuff which is undesirable, imo, and I don't think it is really required. All we want is user be able to automatically tumble stuff from account a to b, without risking someone send them elsewhere, no? I don't think rate limit buys much if anything.

**Comment by nopara73** [comment]
@prusnak > You mentioned "rate limit to 5 times a day" - is this hardcoded in CJ protocol? Or this is just an arbitrary setting mentioned as an example?

It wasn't arbitrary. Rounds were progressing about 5 a day back then. However, today it's more like 1-15. It can grow to many, our anonymity set and denomination can change, even worse, we're planning change the system to unequal mixing at some point in the future. 

On the bright side, I think the rate limit should be set by you what you consider reasonable on your side and Wasabi should work with that limitation in mind.  

> @nopara73 rate limiting would require Trezor remember stuff which is undesirable

There are a bunch of undesirable stuff about coinjoins in a hardware wallet, that's why I am afraid the whole scheme doesn't even make sense in the first place.  
Why rate limit is necessary is that otherwise someone who acquires a trezor could just empty it out by calling autosign many times, which defeats the purpose of a hardware wallet.  
The point of rate limiting is to not be able to do that within a timeframe that the user recognizes his trezor is lost and uses its mnemonics. Unfortunately some balance sucking is unavoidable, so I'm really not sure what to do about it.  

There are two approaches. Generic autosign and Wasabi specific autosign. Generic autosign may be quite hard to implement in a secure way, however Wasabi specific autosign could go a longer way, since that could check the exact format and requirements of the coinjoins.

But for that we need to wait until our coinjoins are set in stone. Maybe we should just implement partial hardware wallet integration after all. We have a good wallet management system. So a user could setup two wallets:  

1. Hardware wallet capable - no coinjoin
2. Coinjoin capable - no hardware wallet

I'm not happy about this, but if a generic autosign is just insecure no matter how it's implemented, then there's no good solution here.

**Comment by dpc** [comment]
> Why rate limit is necessary is that otherwise someone who acquires a trezor could just empty it out by calling autosign many times, which defeats the purpose of a hardware wallet.

Do you mean "empty it out" by making user continuously pay fees etc.? At very least there is less motivation for the attacker to even try, if it doesn't make them any money.

Another problem with rate-limiting is that I don't think Trezor has any idea what time it is (I'm not sure about it, but I think that's the csase), and has to rely on what host would tell it, which can be gamed by an attacker.

Maybe instead of rate-limiting, we could have a counter on how many times given certificate could be used. This way trezor would have to keep maybe a digest + counter per pre-signed certificate, with some fixed number of outstanding certificates issues like this.

**Comment by nopara73** [comment]
> Do you mean "empty it out" by making user continuously pay fees etc.? At very least there is less motivation for the attacker to even try, if it doesn't make them any money.

There are coinjoin coordinator fees, too, so there's no incentive misalignment here.

> Maybe instead of rate-limiting, we could have a counter on how many times given certificate could be used. This way trezor would have to keep maybe a digest + counter per pre-signed certificate, with some fixed number of outstanding certificates issues like this.

Suddenly I don't see why it would be a bad idea. It sounds pretty workable.
