### ISSUE TITLE
Hardware Wallet: Coldcard Support

### ISSUE THREAD

**Issue by Transisto** [zkSNACKs/Meta#38]
I believe the ColdCard hardware wallet is the most underrated wallet out there.
https://coldcardwallet.com/

I know Wasabi Harware support is on the backburner but I'm putting out there in case Coinkine would want to expand it's wallet offering. I see a great synergy between the two company since the main focus is on Bitcoin and high level of professionalism.

The only hardware wallet that has support for Bitcoin Core. 
https://github.com/Coldcard/firmware/blob/master/docs/bitcoin-core-usage.md

128kb of free flash for custom development.
https://github.com/Coldcard/firmware/blob/master/docs/dev-access.md

> Automatically
>  Sign all the transactions, if
> 99% of the coin comes back to one of our addresses.
> rate limit to 5 times a day,
> feerate is lower than 2 sat/b
> etc...
from
https://github.com/zkSNACKs/Meta/issues/30

Coldcard already has a Timeout feature that can be set to "Never" and a Max Network Fee protection setting.

**Comment by nopara73** [comment]
Some of us have cold cards, so out of convenience it could be the first hw wallets to add. However hardware wallet integration is 1. problematic, because something like autosign must be implemented inside the hardware wallet itself to handle coinjoin, which may affect the security of these wallets.  

Of course hacky solutions are always possible, but I'm not keen of them.  

Same discussion: 
https://github.com/zkSNACKs/Meta/issues/31
https://github.com/zkSNACKs/Meta/issues/30
