### ISSUE TITLE
Make sure https://en.bitcoin.it/wiki/Privacy#Wasabi_Wallet is accurate

### ISSUE THREAD

**Issue by Transisto** [zkSNACKs/Meta#47]
https://en.bitcoin.it/wiki/Privacy#Wasabi_Wallet

> For this reason coinjoins can only be of fixed amounts of around 0.1 BTC

I know at least this is wrong.

**Comment by Transisto** [comment]
Current text : 

```
Wasabi Wallet
Wasabi Wallet is a wallet that implements CoinJoin. It is open source and written in C#. The package includes Tor and all traffic goes through it, so IP addresses are well hidden. It is very easy to install and use. The wallet includes all standard privacy tech like a Deterministic wallet and warnings against address reuse, as well as a nice interface for choosing which UTXOs to spend which can help with coin control. The wallet uses Client-side block filtering to obtain its own transaction history in a private way.

CoinJoins happen between users without any liquidity provider middlemen. For this reason coinjoins can only be of fixed amounts of around 0.1 BTC. The coinjoins happen at fixed times when a coinjoin round happens, which is approximately once every hour and a half. These figures are correct as of 2018.

User's wallets connect to a centralized server which coordinates the CoinJoin. The wallet uses chaumian blind signatures (which is very similar to the cryptography used in blinded bearer certificates) so that this server or anyone else does not learn the true linkage between transaction inputs and outputs. The server is run by the zkSnacks company which has developed Wasabi Wallet, the company makes its income by taking a small fee (of 0.03% per participant as of 2018) from each coinjoin transaction.
```

**Comment by nopara73** [comment]
> For this reason coinjoins can only be of fixed amounts of around 0.1 BTC

The next sentence says: "These figures are correct as of 2018." So this is actually correct, nevertheless: this is how I would make the text more accurate:

# Text

Wasabi Wallet is a wallet that implements CoinJoin. It is open source and written in C#**, .NET Core**. The package includes Tor and all traffic **between the clients and the server** goes through it, so IP addresses are ~well~ hidden. It is ~very~ easy to install and use. The wallet includes all standard privacy tech like a **Hierarchical** Deterministic wallet and **warnings against** address reuse **avoidance**, as well as ~a nice interface for choosing which UTXOs to spend which can help with~ **mandatory** coin control. The wallet uses Client-side block filtering to obtain its own transaction history in a private way.

CoinJoins happen between users without any liquidity provider middlemen. ~For this reason coinjoins can only be of fixed amounts of around 0.1 BTC. **As of the beginning of 2019,** ~The~ coinjoins happen ~at fixed times when a coinjoin round happens, which is~ approximately once every hour and a half. ~These figures are correct as of 2018.~

~User's~ **Users'** wallets connect to a ~centralized~ server which coordinates the CoinJoin. The wallet uses ~chaumian~ **schnorr** blind signatures (which is ~very~ similar to the cryptography used in **chaumian blind signatures and** blinded bearer certificates) so that this server or anyone else does not learn the ~true~ linkage between **the mixed** transaction inputs and outputs. The server is run by the ~zkSnacks~ **zkSNACKs** company which has developed Wasabi Wallet, the company makes its income by taking a ~small~ fee (of ~0.03%~ **0.17%** per participant as of ~2018~ **2019**) from each coinjoin transaction.

# Note on fees

The text said 0.03% per participant, but it's actually 0.003% per anonymity set gained, which would be 0.3% per participant assuming 100 participants per round, however today's rounds vary from about 50-59 participants and of course the additional denominations vary from 2-20 participants, so I'd say 0.3*(59/100)=0.17% would be the most accurate value to denote here if we don't want to be too chatty about it and willing to not consider the additional denomination mixes.

@Transisto @chris-belcher any addition/controversy here or should I edit the wiki with these changes? I feel like GitHub is more suitable to discuss these changes, so I won't go ahead and make it now.

**Comment by chris-belcher** [comment]
Yes edit it. See https://en.wikipedia.org/wiki/Wikipedia:Be_bold

**Comment by nopara73** [comment]
Done.
